name: AWS IAC
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
defaults:
  run:
    working-directory: core-env/aws
permissions:
  id-token: write
jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          role-to-assume: arn:aws:iam::218691292270:role/sedemo-iac-pipeline-role
          aws-region: us-west-2
      - name: Verify AWS identity
        run: |
          # Your commands that require AWS credentials
          aws sts get-caller-identity
      - name: Verify Tofu
        uses: opentofu/setup-opentofu@v1
      - run: tofu init
      - id: plan
        run: tofu plan -no-color -var-file=default.tfvars